name: freelancer_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"


dependencies:
  flutter:
    sdk: flutter
  http:
  sqflite:
  path:
  fluttertoast:
  google_fonts: 2.2.0
  flutter_spinkit: ^5.1.0
  get:
  get_storage:
  dio:
  cached_network_image:
  image_picker:
  firebase_core: ^1.13.0
  cloud_firestore: ^3.1.10
  intl: 
  file_picker: 4.5.1
  http_parser: 4.0.1
  flutter_launcher_icons: 0.9.2
  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - lib/assets/

  uses-material-design: true
